name: Build OpenWrt Redmi AX3000

on:
  workflow_dispatch:
    inputs:
      hw_version:
        description: 'AX3000 hardware version (V1 or V2)'
        required: true
        default: 'V1'
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout workflow repo
      uses: actions/checkout@v4
      with:
        path: workflow

    - name: Checkout OpenWrt
      uses: actions/checkout@v4
      with:
        repository: openwrt/openwrt
        ref: master
        path: openwrt

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential clang flex bison g++ gawk \
          gcc-multilib g++-multilib gettext git libncurses5-dev libssl-dev \
          python3-distutils rsync unzip zlib1g-dev file wget

    - name: Add Redmi AX3000 support
      run: |
        cd openwrt
        git clone https://github.com/hzyitc/openwrt-redmi-ax3000 device_patch

        # 复制 package
        if [ -d "device_patch/package" ]; then
          cp -r device_patch/package/* ./package/
          echo "✅ Packages copied."
        else
          echo "⚠️ No package folder found."
        fi

        # 根据硬件版本应用 patch
        HW_VERSION="${{ github.event.inputs.hw_version }}"
        PATCH_DIR="device_patch/patches/$HW_VERSION"
        if [ -d "$PATCH_DIR" ]; then
          for p in "$PATCH_DIR"/*.patch; do
            git apply "$p" && echo "✅ Applied patch $p" || echo "❌ Failed patch $p"
          done
          echo "✅ All patches for $HW_VERSION applied."
        else
          echo "⚠️ No patch folder for $HW_VERSION found."
        fi

    - name: Apply custom configuration
      run: |
        cp workflow/.config openwrt/.config
        cd openwrt
        make defconfig

    - name: Download sources
      run: |
        cd openwrt
        make download -j$(nproc)

    - name: Build OpenWrt
      run: |
        cd openwrt
        make -j$(nproc) V=s 2>&1 | tee ../build_log.txt

    - name: Collect firmware
      run: |
        cd openwrt
        mkdir -p ../firmware
        find bin/targets/ -type f -name "*redmi-ax3000*squashfs-factory.ubi" -exec cp {} ../firmware/ \;
        find bin/targets/ -type f -name "*redmi-ax3000*sysupgrade*" -exec cp {} ../firmware/ \;

    - name: Upload firmware
      uses: actions/upload-artifact@v4
      with:
        name: openwrt-redmi-ax3000
        path: firmware

    - name: Upload build log
      uses: actions/upload-artifact@v4
      with:
        name: build-log
        path: build_log.txt
