name: Build OpenWrt Redmi AX3000

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout workflow repo
      uses: actions/checkout@v4
      with:
        path: workflow

    - name: Checkout OpenWrt
      uses: actions/checkout@v4
      with:
        repository: openwrt/openwrt
        ref: master
        path: openwrt

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential clang flex bison g++ gawk \
          gcc-multilib g++-multilib gettext git libncurses5-dev libssl-dev \
          python3-distutils rsync unzip zlib1g-dev file wget

    - name: Add Redmi AX3000 support
      run: |
        cd openwrt
        git clone https://github.com/hzyitc/openwrt-redmi-ax3000 device_patch
        # 打入设备相关支持文件
        cp -r device_patch/target/linux/ipq60xx ./target/linux/
        cp -r device_patch/package/* ./package/

    - name: Apply custom configuration
      run: |
        cp workflow/.config openwrt/.config
        cd openwrt
        make defconfig

    - name: Download sources
      run: |
        cd openwrt
        make download -j$(nproc)

    - name: Build
      run: |
        cd openwrt
        make -j$(nproc) V=s

    - name: Collect firmware
      run: |
        cd openwrt
        mkdir -p ../firmware
        find bin/targets/ -type f -name "*redmi-ax3000*squashfs-factory.ubi" -exec cp {} ../firmware/ \;
        find bin/targets/ -type f -name "*redmi-ax3000*sysupgrade*" -exec cp {} ../firmware/ \;

    - name: Upload firmware
      uses: actions/upload-artifact@v4
      with:
        name: openwrt-redmi-ax3000
        path: firmware
